"""create interview schema

Revision ID: 2fcf066ac617
Revises: 
Create Date: 2026-08-08 16:30:44.133639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fcf066ac617'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('creating', 'in_progress', 'ending', 'evaluating', 'summarized', 'failed', 'cancelled', name='sessionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('rolling_summary', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_status'), 'interview_sessions', ['status'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.SmallInteger(), nullable=False),
    sa.Column('readiness', sa.String(length=32), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('improvements', sa.JSON(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('model_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 100', name='ck_overall_score'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'version', name='uq_evaluation_session_version')
    )
    op.create_index(op.f('ix_evaluations_session_id'), 'evaluations', ['session_id'], unique=False)
    op.create_table('session_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('skill_tag', sa.String(length=100), nullable=True),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'current', 'answered', 'skipped', 'not_attempted', name='questionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('score_note', sa.Text(), nullable=True),
    sa.Column('follow_up_count', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 5)', name='ck_question_score'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'position', name='uq_session_question_position')
    )
    op.create_index(op.f('ix_session_questions_session_id'), 'session_questions', ['session_id'], unique=False)
    op.create_table('competency_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 5', name='ck_competency_score'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_scores_evaluation_id'), 'competency_scores', ['evaluation_id'], unique=False)
    op.create_table('interview_turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('client_message_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('received', 'processing', 'completed', 'failed', name='turnstatus', native_enum=False, length=16), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['session_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'client_message_id', name='uq_turn_client_message')
    )
    op.create_index(op.f('ix_interview_turns_session_id'), 'interview_turns', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('system', 'assistant', 'user', 'tool', name='messagerole', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('client_message_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['session_questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'client_message_id', name='uq_message_client_id')
    )
    op.create_index('ix_messages_session_created', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_table('question_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 5', name='ck_feedback_score'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['session_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'question_id', name='uq_feedback_question')
    )
    op.create_index(op.f('ix_question_feedback_evaluation_id'), 'question_feedback', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_question_feedback_question_id'), 'question_feedback', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_feedback_question_id'), table_name='question_feedback')
    op.drop_index(op.f('ix_question_feedback_evaluation_id'), table_name='question_feedback')
    op.drop_table('question_feedback')
    op.drop_index('ix_messages_session_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_interview_turns_session_id'), table_name='interview_turns')
    op.drop_table('interview_turns')
    op.drop_index(op.f('ix_competency_scores_evaluation_id'), table_name='competency_scores')
    op.drop_table('competency_scores')
    op.drop_index(op.f('ix_session_questions_session_id'), table_name='session_questions')
    op.drop_table('session_questions')
    op.drop_index(op.f('ix_evaluations_session_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_interview_sessions_status'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
