"""add question title

Revision ID: bae8f7bfd05a
Revises: 2fcf066ac617
Create Date: 2026-08-08 17:22:50.577132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae8f7bfd05a'
down_revision: Union[str, Sequence[str], None] = '2fcf066ac617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_questions', sa.Column('title', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_questions', 'title')
    # ### end Alembic commands ###
