"""use pgvector for project embeddings

Revision ID: e8f2a3b5c012
Revises: d7e1c2f4a901
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


revision: str = "e8f2a3b5c012"
down_revision: Union[str, Sequence[str], None] = "d7e1c2f4a901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # The previous MVP stored embeddings as JSON. Indexed data is regenerated by
    # the project background task, so replace that temporary column with vector.
    op.drop_column("project_data", "embedding")
    op.add_column("project_data", sa.Column("embedding", Vector(1536), nullable=True))
    op.execute("UPDATE project_data SET status = 'pending', error = NULL")
    op.create_index(
        "ix_project_data_embedding_cosine",
        "project_data",
        ["embedding"],
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )


def downgrade() -> None:
    op.drop_index("ix_project_data_embedding_cosine", table_name="project_data")
    op.drop_column("project_data", "embedding")
    op.add_column("project_data", sa.Column("embedding", sa.JSON(), nullable=True))
